apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-demo.fullname" . }}
  labels:
    {{- include "flask-demo.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "flask-demo.name" . }}
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
